language: ruby
services:
- docker
before_script:
- docker build -t limarka:customizado .
script: 
- docker run --mount src=`pwd`,target=/trabalho,type=bind limarka:customizado exec
- mv xxx*.pdf $PDF
after_failure:
  - cat test/latex/exemplo-minimo/xxx-*.log
before_deploy:
  - git config --local user.name $NOME
  - git config --local user.email $EMAIL
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $TOKEN
  file: $PDF
  skip_cleanup: true
  draft: true
