---
instituicao: Uninorte
author: Kalebe Silva
title: Gasolina
local: Rio Branco - AC
date: '2022'
capa_pdf_caminho: ''
titulacao: bacharel
curso: Sistemas de informação
programa: Programa de Graduação em Sistemas
area_de_concentracao: Computação
linha_de_pesquisa: ''
coorientador: ''
orientador: Josana Nishirira e João Pedro
referencias_caminho: referencias.bib
proposito: ''
resumo: ''
palavras_chave: ''
keywords: ''
abstract_texto: ''
resumen: ''
palabras_clave: ''
resume: ''
mots_cles: ''
siglas: false
simbolos: 
dedicatoria: ''
agradecimentos: ''
epigrafe: ''
avaliador2: Vander
aprovacao_dia: '1'
avaliador1: João Pedro
avaliador3: ''
graduacao: true
especializacao: false
mestrado: false
doutorado: false
tipo_do_trabalho: Monografia
incluir_ficha_catalografica: false
folha_de_aprovacao: false
projeto: true
apendices: true
anexos: false
errata: false
referencias_sistema: alf
lista_ilustracoes: false
lista_quadros: false
lista_tabelas: false

---
